config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  delete 'articles/:id', to: 'articles#destroy', as: :delete_article
  resources :articles, only: [:create, :index, :edit, :update, :new, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy]

  def index
    @article = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(articles_params)
    @article.save
    redirect_to article_path(@article.id)
  end

  def edit
  end

  def update
    @article.update(articles_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def articles_params
    params.require(:article).permit(:title, :content)
  end

  def find_article
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= form_with model: @article do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

<p><%= link_to 'Delete article', article_path(@article), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></p>

<p><%= link_to 'Back to list', articles_path %></p>

app/views/articles/index.html.erb
<h1>My articles</h1>

<% @article.each do |t| %>
  <h2>
    <%= link_to t.title, article_path(t.id) %> -
    <%= link_to 'Delete article', delete_article_path(t.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
  </h2>
  <p><%=t.content%></p>

<% end %>

<p><%= link_to "+ Add a new article", new_article_path %></p>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= form_with model: @article do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

<p><%= link_to 'Back to list', articles_path %></p>

app/views/articles/show.html.erb
<h1>Article <%= @article.title %> content</h1>

<p><%= @article.content %></p>

<p><%= link_to 'Delete article', article_path(@article), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></p>

<p><%= link_to 'Edit this article', edit_article_path(@article.id) %></p>

<p><%= link_to 'Back to list', articles_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>